main: uk.co.harieo.seasons.core.SeasonsCore
version: 2.5.1
name: Seasons
author: Harieo
api-version: 1.13
softdepend:
  - 'PlaceholderAPI'

commands:
  season:
    description: Display the current Seasons information
    aliases: [seasons]
  changeday:
    description: Changes the day in a world
  changeweather:
    description: Changes the weather in a world
  changeseason:
    description: Changes the season in a world
  changeyear:
    description: Changes the year in a world

permissions:
  seasons.*:
    description: Use all seasons commands
    default: op
    children:
      seasons.change.*: true
      seasons.reload: true
      seasons.import: true
  seasons.change.*:
    description: Use all the change commands
    default: op
    children:
      seasons.change.day: true
      seasons.change.weather: true
      seasons.change.season: true
  seasons.change.day:
    description: Change the day in a world
    default: op
  seasons.change.weather:
    description: Change the weather in a world
    default: op
  seasons.change.season:
    description: Change the season in a world
    default: op
  seasons.change.year:
    description: Change the year in a world
    default: op
  seasons.reload:
    description: Reload the configuration for seasons
    default: op
  seasons.import:
    description: Allows you to import a world into seasons
    default: op
  seasons.config:
    description: Allows you to see your configuration options in-game
    default: op